# 서울시 100m 격자 성·연령별 문화누리 대상인구 추정

## 목적
- 100m 성·연령별 인구 통계로 격자별 구성비 산출
- 구성비가 없는 격자는 동일 행정동 구성비로 대체
- 격자별 문화누리 대상인구를 성별·연령대로 배분하고 정수화

In [1]:
import pathlib

import geopandas as gpd
import numpy as np
import pandas as pd

BASE_PATH = pathlib.Path.cwd().resolve()
if not (BASE_PATH / "data").exists():
    BASE_PATH = next(p for p in BASE_PATH.parents if (p / "data").exists())

RAW_PATH = BASE_PATH / "data" / "raw"
PROCESSED_PATH = BASE_PATH / "data" / "processed"
AGE_GENDER_PATH = (
    RAW_PATH / "population" / "grid" / "100m_sex_age_population_2024_10"
)
GRID_FILE = (
    PROCESSED_PATH / "estimated_target_population"
    / "서울시_100m_문화누리추정인구수.gpkg"
)
OUTPUT_FILE = (
    PROCESSED_PATH / "estimated_target_population"
    / "서울시_격자_100m_문화누리대상자_성연령별_인구수.csv"
)

assert GRID_FILE.exists(), "3번 노트북 결과가 없습니다."
grid = gpd.read_file(GRID_FILE)

## 성·연령별 100m 격자 데이터 불러오기

In [2]:
def read_shp_file(age):
    PATH = AGE_GENDER_PATH / age
    
    shp_list = list(PATH.rglob("vl_blk.shp")) # rglob은 하위 폴더까지 모두 탐색
    
    print(f'{age} shp 데이터 개수: {len(shp_list)}')
    
    gdf_list = []
    
    for shp in shp_list:
        temp = gpd.read_file(shp,
                             encoding = 'utf-8')
        temp["연령대"] = shp.parent.parent.parent.name
        temp["성별"] = shp.parent.parent.name
        temp["시군구"] = shp.parent.name
        
        gdf_list.append(temp)
    
    gdf_con = pd.concat(gdf_list, 
                       ignore_index= True,
                       axis = 0) # 데이터 파일마다 중복되는 인덱스 무시하고 새로 생성
    
    result = gpd.GeoDataFrame(gdf_con,
                              geometry = "geometry",
                              crs = gdf_list[0].crs)
    
    print(f'\ncrs: {result.crs}')
    print(f'\n지오타입 {result.geometry.geom_type.unique()}')
    print(f'\n데이터 구조 {result.shape}')
    display(result.head())
        
    return result

category_list = [
 '총인구',
 '유아인구', # 만 0 - 4세
 '유소년인구', # 만 0 -14세
 '초등학생인구',
 '중학생인구',
 '고등학생인구', 
 '20대인구',
 '30대인구',
 '40대인구',
 '50대인구',
 '60대인구',
 '70대인구',
 '80대인구',
 '90대인구',
 '100세이상인구'
 ]


grid_list = []
for age in category_list:
    result = read_shp_file(age)
    
    grid_list.append(result)
    
grid_stat = pd.concat(grid_list,
                      axis = 0,
                      ignore_index=True)
print('='*100)
print(f'\ncrs: {grid_stat.crs}')
print(f'\n지오타입 {grid_stat.geometry.geom_type.unique()}')
print(f'\n데이터 구조 {grid_stat.shape}')
display(grid_stat.head(20))

총인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",총인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",총인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",총인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",총인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",총인구,남성,강남구

유아인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",유아인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",유아인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",유아인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",유아인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",유아인구,남성,강남구

유소년인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",유소년인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",유소년인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",유소년인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",유소년인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",유소년인구,남성,강남구

초등학생인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",초등학생인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",초등학생인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",초등학생인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",초등학생인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",초등학생인구,남성,강남구

중학생인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",중학생인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",중학생인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",중학생인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",중학생인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",중학생인구,남성,강남구

고등학생인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",고등학생인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",고등학생인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",고등학생인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",고등학생인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",고등학생인구,남성,강남구

20대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",20대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",20대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",20대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",20대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",20대인구,남성,강남구

30대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",30대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",30대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",30대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",30대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",30대인구,남성,강남구

40대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",40대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",40대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",40대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",40대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",40대인구,남성,강남구

50대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",50대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",50대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",50대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",50대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",50대인구,남성,강남구

60대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",60대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",60대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",60대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",60대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",60대인구,남성,강남구

70대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",70대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",70대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",70대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",70대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",70대인구,남성,강남구

80대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",80대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",80대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",80대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",80대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",80대인구,남성,강남구

90대인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",90대인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",90대인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",90대인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",90대인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",90대인구,남성,강남구

100세이상인구 shp 데이터 개수: 75

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (194043, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",100세이상인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",100세이상인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",100세이상인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",100세이상인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",100세이상인구,남성,강남구

====================================================================================================

crs: EPSG:5179

지오타입 ['Polygon']

데이터 구조 (2910645, 7)

,gid,lbl,val,geometry,연령대,성별,시군구
0,다사565474,None,NaN,"POLYGON ((956500 1947400, 956500 1947500, 9566...",총인구,남성,강남구
1,다사565475,None,NaN,"POLYGON ((956500 1947500, 956500 1947600, 9566...",총인구,남성,강남구
2,다사566473,None,NaN,"POLYGON ((956600 1947300, 956600 1947400, 9567...",총인구,남성,강남구
3,다사566474,None,NaN,"POLYGON ((956600 1947400, 956600 1947500, 9567...",총인구,남성,강남구
4,다사566475,None,NaN,"POLYGON ((956600 1947500, 956600 1947600, 9567...",총인구,남성,강남구
5,다사566476,None,NaN,"POLYGON ((956600 1947600, 956600 1947700, 9567...",총인구,남성,강남구
6,다사567472,None,NaN,"POLYGON ((956700 1947200, 956700 1947300, 9568...",총인구,남성,강남구
7,다사567473,None,NaN,"POLYGON ((956700 1947300, 956700 1947400, 9568...",총인구,남성,강남구
8,다사567474,None,NaN,"POLYGON ((956700 1947400, 956700 1947500, 9568...",총인구,남성,강남구
9,다사567475,None,NaN,"POLYGON ((956700 1947500, 956700 1947600, 9568...",총인구,남성,강남구
10,다사567476,None,NaN,"POLYGON ((956700 1947600, 956700 1947700, 9568...",총인구,남성,강남구
11,다사567477,None,NaN,"POLYGON ((956700 1947700, 956700 1947800, 9568...",총인구,남성,강남구
12,다사568472,None,NaN,"POLYGON ((956800 1947200, 956800 1947300, 9569...",총인구,남성,강남구
13,다사568473,None,NaN,"POLYGON ((956800 1947300, 956800 1947400, 9569...",총인구,남성,강남구
14,다사568474,None,NaN,"POLYGON ((956800 1947400, 956800 1947500, 9569...",총인구,남성,강남구
15,다사568475,None,NaN,"POLYGON ((956800 1947500, 956800 1947600, 9569...",총인구,남성,강남구
16,다사568476,None,NaN,"POLYGON ((956800 1947600, 956800 1947700, 9569...",총인구,남성,강남구
17,다사568477,None,NaN,"POLYGON ((956800 1947700, 956800 1947800, 9569...",총인구,남성,강남구
18,다사568478,None,NaN,"POLYGON ((956800 1947800, 956800 1947900, 9569...",총인구,남성,강남구
19,다사568479,None,NaN,"POLYGON ((956800 1947900, 956800 1948000, 9569...",총인구,남성,강남구

## 성·연령별 데이터 전처리
- 원자료 결측은 0으로 처리
- 중복 격자는 격자·성별·연령대 기준으로 합산
- 0-5세, 6-14세, 15-19세 연령대 파생

In [3]:
# 칼럼 정리
grid_stat_cleaning = grid_stat[["gid", "시군구", 'val', '성별', '연령대', 'geometry']].copy()

# 칼럼명 변경
grid_stat_cleaning = grid_stat_cleaning.rename(columns = {"gid": "GRID_CD",
                                                          "val": "인구수"})

# 데이터 타입 변경
grid_stat_cleaning["인구수"]=  pd.to_numeric(grid_stat_cleaning["인구수"],
                                          errors = "coerce")
print(grid_stat_cleaning['인구수'].dtypes)

# 결측치 처리
grid_stat_clean = grid_stat_cleaning.copy()
grid_stat_clean["인구수"] = grid_stat_clean["인구수"].fillna(0)

print('전처리 확인')
print(grid_stat_clean['인구수'].isna().sum())

float64
전처리 확인
0

In [4]:
# 데이터 구조 정리: 그룹화
grid_stat_group = grid_stat_clean.groupby(["GRID_CD", "시군구", "성별", "연령대"], as_index=False)["인구수"].sum()

print(f"집계 전 구조: {grid_stat_clean.shape}")
print(f"집계 후 구조: {grid_stat_group.shape}")
print(f"중복 확인: {grid_stat_group[['GRID_CD', '시군구', '성별', '연령대']].duplicated().sum()}")

집계 전 구조: (2910645, 6)
집계 후 구조: (2910645, 5)

중복 확인: 0

In [5]:
# 파생 연령대 생성(6-14, 15-19세) 위해 wide 형태로 변경
grid_stat_wide = grid_stat_group.pivot_table(index=["GRID_CD", "시군구","성별"],
                                            columns = "연령대",
                                            values = "인구수",
                                            aggfunc = "sum",
                                            fill_value = 0
).reset_index()

grid_stat_wide.columns.name = None

age_over_20_cols = ["20대인구", "30대인구", "40대인구", "50대인구",
    "60대인구", "70대인구", "80대인구", "90대인구", "100세이상인구"]

grid_stat_wide["0-19세"] = grid_stat_wide["총인구"] - grid_stat_wide[age_over_20_cols].sum(axis=1)

# 유아 인구 (0-5세)
grid_stat_wide["0-5세"] = grid_stat_wide["유아인구"]

# 6-14세
grid_stat_wide["6-14세"] = grid_stat_wide["유소년인구"] - grid_stat_wide["0-5세"]

# 15-19세
grid_stat_wide["15-19세"] = grid_stat_wide["0-19세"] - grid_stat_wide["유소년인구"]

print("0-19세 음수:", (grid_stat_wide["0-19세"] < 0 ).sum())
print("6~14세 음수:", (grid_stat_wide["6-14세"] < 0).sum())
print("15~19세 음수:", (grid_stat_wide["15-19세"] < 0).sum())

0-19세 음수: 0
6~14세 음수: 0
15~19세 음수: 0

In [6]:
# 데이터 점검: 연령별 총인구와 남여합 비교
age_cols = [
    "0-5세", "6-14세", "15-19세",
    "20대인구", "30대인구", "40대인구", "50대인구",
    "60대인구", "70대인구", "80대인구", "90대인구", "100세이상인구"
]
stat_total = grid_stat_wide[grid_stat_wide["성별"] == '총인구'].set_index("GRID_CD")[age_cols]
stat_male = grid_stat_wide[grid_stat_wide["성별"] == '남성'].set_index("GRID_CD")[age_cols]
stat_female = grid_stat_wide[grid_stat_wide["성별"] == '여성'].set_index("GRID_CD")[age_cols]

stat_whole = stat_total - (stat_female + stat_male)

display(stat_whole.describe())

# 개인정보 보호, 마스킹, 반올림 등의 영향으로 인해 총인구수와 남여 인구수 합이 가법적으로 일치하지 않도록 설계된 것으로 보임
# 파생변수(6-14세, 15-19세)에서는 평균적으로 남여합이 많았으며, 나머지 연령대에서는 총인구수가 남여 합을 상회하는 수치
# 격자별 인구 통계 테이블에서는 앞선 분석에서 추정한 문화누리대상자에 대한 남여 비율 기반 추정이 핵심이므로,
# 총 인구수는 검증 혹은 보조 데이터로 활용할 필요가 있다고 판단, 별도의 처리를 하지 않기로 결정.

,0-5세,6-14세,15-19세,20대인구,30대인구,40대인구,50대인구,60대인구,70대인구,80대인구,90대인구,100세이상인구
count,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000,64681.000000
mean,0.631468,-0.122633,-3.150755,0.289513,0.253877,0.278567,0.254603,0.291925,0.413104,0.764614,0.188834,0.000216
std,1.898720,2.479069,6.495554,1.284876,1.211227,1.283601,1.231487,1.324790,1.554523,2.010806,1.056253,0.039320
min,0.000000,-10.000000,-53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000

## 문화누리 대상인구 성·연령별 배분
- 격자별 성·연령 구성비를 우선 사용
- 대상인구는 있으나 구성비가 없는 격자는 동일 행정동 구성비 사용
- 내림 후 소수점이 큰 순서로 잔여 인원을 배분하여 격자별 정수 총량 보존

In [7]:
est_cols = ["GRID_CD", "시군구", "성별",
    "0-5세", "6-14세", "15-19세",
    "20대인구", "30대인구", "40대인구", "50대인구",
    "60대인구", "70대인구", "80대인구", "90대인구", "100세이상인구"
]

grid_est = grid_stat_wide[est_cols].copy()
grid_est = grid_est[grid_est["성별"].isin(['남성', '여성'])].copy()

# wide -> long
grid_age_gender = grid_est.melt(
    id_vars=["GRID_CD", "시군구", "성별"],
    value_vars=age_cols,
    var_name="연령대",
    value_name="인구수"
)

print('데이터 구조:', grid_age_gender.shape)
# 데이터 구조: (1552344, 5)

# 기본 격자 테이블에서 중복 시군구의 격자들을 격자 코드 중심으로 인구를 합산 한 뒤, 중심점 기준으로 병합, 하나의 시군구에 귀속시켰다.
# 인구 통계 격자 데이터에서도 동일한 문제가 반복될 수 있어, 격자코드 - 성별 - 연령대 중복 값을 확인 후 인구 수를 하나로 통합하였다.
 
grid_gu_count = (
    grid_age_gender
    .groupby("GRID_CD")["시군구"]
    .nunique()
    .reset_index(name="시군구_개수")
)

print("복수 시군구에 포함된 GRID_CD 수:")
print((grid_gu_count["시군구_개수"] > 1).sum())

# 최소 인구수 0으로 처리
grid_age_gender["인구수"] = grid_age_gender["인구수"].clip(lower=0)

grid_age_gender_clean = grid_age_gender.groupby(by = ["GRID_CD", "성별", "연령대"], as_index=False).agg({"인구수": 'sum'})

print('\n시군구 병합 후 중복 확인')
print(grid_age_gender_clean[["GRID_CD", "성별", "연령대"]].duplicated().sum())

# 격자 별 남여 인구수 합 칼럼
grid_age_gender_clean["격자별전연령인구수합"] = grid_age_gender_clean.groupby(["GRID_CD"])["인구수"].transform('sum')
grid_age_gender_clean.head()

# 성연령별 인구 비중 칼럼 : 칼럼
grid_age_gender_clean["격자별인구비중"] = np.where(grid_age_gender_clean["격자별전연령인구수합"] > 0,
                                      grid_age_gender_clean["인구수"] / grid_age_gender_clean["격자별전연령인구수합"],
                                      0)

print('\n오류 점검')
print(((grid_age_gender_clean["격자별전연령인구수합"] <= 0) & (grid_age_gender_clean["격자별인구비중"]>0)).sum())


ratio_check = grid_age_gender_clean.groupby("GRID_CD", as_index=False)["격자별인구비중"].sum().rename(columns = {'격자별인구비중': "격자별인구비중합"})
print('\n격자별인구비중 데이터 검토')
print(ratio_check["격자별인구비중합"].describe())
print('인구 비중 합이 1인 격자 개수', (ratio_check["격자별인구비중합"] == 1).sum())
print('인구 비중 합이 0인 격자 개수', (ratio_check["격자별인구비중합"] == 0).sum())
print('인구 비중 합이 1이 아니면서 0도 아닌 격자 개수', ((ratio_check["격자별인구비중합"] != 1) & (ratio_check["격자별인구비중합"] != 0)).sum())

ratio_check[(ratio_check["격자별인구비중합"] != 1) & (ratio_check["격자별인구비중합"] != 0)].sort_values('격자별인구비중합', 
                                                                                         ascending=True)

# 인구 비중 합이 1인 격자 개수 28878
# 인구 비중 합이 0인 격자 개수 35590
# 인구 비중 합이 1이 아니면서 0도 아닌 격자 개수 213
# 이상치 후보 격자 확인 결과, 실제 인구비중합은 1로, 부동소수점으로 인한 집계 오류였던 것으로 확인되었다.

데이터 구조: (1552344, 5)

복수 시군구에 포함된 GRID_CD 수:
2984

시군구 병합 후 중복 확인

0

오류 점검
0

격자별인구비중 데이터 검토
count    61652.000000
mean         0.468955
std          0.499039
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: 격자별인구비중합, dtype: float64
인구 비중 합이 1인 격자 개수 28694
인구 비중 합이 0인 격자 개수 32740
인구 비중 합이 1이 아니면서 0도 아닌 격자 개수 218

        GRID_CD  격자별인구비중합
1164   다사384533       1.0
1556   다사390516       1.0
1973   다사396444       1.0
2069   다사397506       1.0
2305   다사400438       1.0
...         ...       ...
60257  다사689431       1.0
60301  다사689495       1.0
60332  다사690432       1.0
19748  다사509510       1.0
44369  다사608544       1.0

[218 rows x 2 columns]

In [8]:
grid_ratio = grid_age_gender_clean.copy()
grid_ratio.head()

print(grid_ratio[["GRID_CD", "연령대", "성별"]].duplicated().sum())
# 72696

grid_merge = grid.merge(grid_ratio, 
                        on = "GRID_CD",
                        how = 'left')

print('병합 후 점검')
print('결합 전 기본 격자 구조', grid.shape)
print('결합 전 성연령 격자 구조', grid_ratio.shape)
print('줄어든 격자 개수', len(grid_ratio) - len(grid_merge))
print('데이터 구조', grid_merge.shape)
print('결측치', grid_merge.isna().sum())
print('격자_연령_성별 중복', grid_merge[["GRID_CD", "연령대", "성별"]].duplicated().sum())


    # 0
    # 병합 후 점검
    # 결합 전 기본 격자 구조 (60528, 14)
    # 결합 전 성연령 격자 구조 (1479648, 6)
    # 줄어든 격자 개수 26976
    # 데이터 구조 (1452672, 19)
    # 결측치 GRID_CD           0
    # 행정동코드             0
    # 시군구               0
    # 행정동               0
    # 중심점_x             0
    # 중심점_y             0
    # 원본_인구수            0
    # 주거면적              0
    # 주택수               0
    # 공시지가              0
    # 추정_인구수            0
    # 문화누리대상자_추정_인구수    0
    # GRID_CD_500       0
    # geometry          0
    # 성별                0
    # 연령대               0
    # 인구수               0
    # 격자별전연령인구수합        0
    # 격자별인구비중           0
    # dtype: int64
    # 격자_연령_성별 중복 0

0

병합 후 점검
결합 전 기본 격자 구조 (60528, 14)
결합 전 성연령 격자 구조 (1479648, 6)
줄어든 격자 개수 26976
데이터 구조 (1452672, 19)

결측치 GRID_CD           0
행정동코드             0
시군구               0
행정동               0
중심점_x             0
중심점_y             0
원본_인구수            0
주거면적              0
주택수               0
공시지가              0
추정_인구수            0
문화누리대상자_추정_인구수    0
GRID_CD_500       0
geometry          0
성별                0
연령대               0
인구수               0
격자별전연령인구수합        0
격자별인구비중           0
dtype: int64

격자_연령_성별 중복 0

In [9]:
# 칼럼명 변경
age_name_map = {
    "20대인구": "20-29세",
    "30대인구": "30-39세",
    "40대인구": "40-49세",
    "50대인구": "50-59세",
    "60대인구": "60-69세",
    "70대인구": "70-79세",
    "80대인구": "80-89세",
    "90대인구": "90-99세",
    "100세이상인구": "100세-"
}

grid_merge["연령대"] = grid_merge["연령대"].replace(age_name_map)

In [10]:
# 성 연령별 추정 인구수

# 이상치 후보 검토
grid_out = grid_merge.groupby("GRID_CD", as_index = False).agg({"문화누리대상자_추정_인구수": 'first',
                                              "격자별인구비중": 'sum'}
                                             ).rename(columns = {"격자별인구비중": "격자별인구비중합"})

over_idx = (np.isclose(grid_out["문화누리대상자_추정_인구수"], 0)) & (~np.isclose(grid_out["격자별인구비중합"], 0))
under_idx = (~np.isclose(grid_out["문화누리대상자_추정_인구수"], 0)) & (np.isclose(grid_out["격자별인구비중합"], 0))

print(over_idx.sum())
display(grid_out[over_idx].sort_values('격자별인구비중합', ascending=False))

print(under_idx.sum())
display(grid_out[under_idx].sort_values('문화누리대상자_추정_인구수', ascending=False))


# 일부 격자에서는 문화누리대상자 추정 인구수는 존재하지만 성별·연령별 격자 인구비중이 0으로 나타났다. 
# 해당 격자에 격자 단위 성별·연령 분포를 적용하면 문화누리대상자 총량이 소실되므로, 같은 시군구·행정동의 성별·연령별 인구비중으로 대체하였다.
# 이를 통해 격자별 문화누리대상자 총량을 보존하면서 성별·연령대별 배분이 가능하도록 하였다.

0

Empty DataFrame
Columns: [GRID_CD, 문화누리대상자_추정_인구수, 격자별인구비중합]
Index: []

676

        GRID_CD  문화누리대상자_추정_인구수  격자별인구비중합
53857  다사646428        3.203905       0.0
31647  다사564636        2.823872       0.0
30390  다사559604        2.688168       0.0
36719  다사583642        2.659202       0.0
39406  다사593656        2.300399       0.0
...         ...             ...       ...
45857  다사616451        0.009318       0.0
29036  다사554446        0.008342       0.0
16822  다사499466        0.006533       0.0
56097  다사659427        0.006510       0.0
32749  다사569444        0.001373       0.0

[676 rows x 3 columns]

In [11]:
hjd_est = grid_merge[grid_merge["격자별전연령인구수합"] > 0].groupby(["시군구", "행정동", "성별", "연령대"], as_index=False)["인구수"].sum()
hjd_est["행정동_전연령인구수합"] =  hjd_est.groupby(["시군구", "행정동"])["인구수"].transform('sum')
hjd_est["행정동_인구비중"] = hjd_est["인구수"] / hjd_est["행정동_전연령인구수합"]

hjd_est = hjd_est[["시군구", "행정동", "성별", "연령대", "행정동_인구비중"]].copy()

grid_merge_hjd = grid_merge.merge(hjd_est,
                             on = ["시군구", "행정동", "성별", '연령대'],
                             how = 'left')

hjd_ratio_list = list(grid_out.loc[under_idx, "GRID_CD"].unique())

grid_merge_hjd["최종_인구비중"] = np.where(
    grid_merge_hjd["GRID_CD"].isin(hjd_ratio_list), 
                                    grid_merge_hjd["행정동_인구비중"],
                                    grid_merge_hjd["격자별인구비중"]
                                    )

print('\n인구 비중 검토')
ratio_test = grid_merge_hjd.groupby("GRID_CD", as_index=False).agg({"문화누리대상자_추정_인구수": 'first',
                                                                    "최종_인구비중": 'sum'})
print((((ratio_test["문화누리대상자_추정_인구수"] > 0) & (np.isclose(ratio_test["최종_인구비중"], 0))).sum()))

grid_merge_hjd["문화누리대상자_성연령별_추정_인구수"] = grid_merge_hjd["문화누리대상자_추정_인구수"] * grid_merge_hjd["최종_인구비중"]


grid_merge_hjd.head()
pop_check = grid_merge_hjd.groupby("GRID_CD", as_index=False).agg({"문화누리대상자_추정_인구수": 'first',
                                                                "문화누리대상자_성연령별_추정_인구수": 'sum'})
pop_check['인구오차'] = pop_check["문화누리대상자_추정_인구수"] - pop_check["문화누리대상자_성연령별_추정_인구수"]

print('\n인구오차 검정')
print((~np.isclose(pop_check["인구오차"], 0)).sum())

인구 비중 검토

0

인구오차 검정
0

In [12]:
# 정수화 대상 값
grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_raw"] = grid_merge_hjd["문화누리대상자_성연령별_추정_인구수"]

# 내림값과 소수점
grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_floor"] = np.floor(
    grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_raw"]
).astype(int)

grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_소수"] = (
    grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_raw"]
    - grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_floor"]
)

# 격자별 목표 총량
grid_target = (
    grid_merge_hjd
    .groupby("GRID_CD", as_index=False)["문화누리대상자_추정_인구수"]
    .first()
)

grid_target["목표정수"] = grid_target["문화누리대상자_추정_인구수"].round().astype(int)

# 격자별 floor 합계
grid_floor_sum = (
    grid_merge_hjd
    .groupby("GRID_CD", as_index=False)["문화누리대상자_성연령별_추정_인구수_floor"]
    .sum()
    .rename(columns={"문화누리대상자_성연령별_추정_인구수_floor": "floor합계"})
)

grid_target = grid_target.merge(
    grid_floor_sum,
    on="GRID_CD",
    how="left"
)

grid_target["추가배분수"] = (
    grid_target["목표정수"] - grid_target["floor합계"]
).astype(int)

grid_merge_hjd = grid_merge_hjd.merge(
    grid_target[["GRID_CD", "추가배분수"]],
    on="GRID_CD",
    how="left"
)

grid_merge_hjd["추가배분순위"] = (
    grid_merge_hjd
    .sort_values(
        ["GRID_CD", "문화누리대상자_성연령별_추정_인구수_소수"],
        ascending=[True, False]
    )
    .groupby("GRID_CD")
    .cumcount() + 1
)

grid_merge_hjd["추가배분"] = np.where(
    grid_merge_hjd["추가배분순위"] <= grid_merge_hjd["추가배분수"],
    1,
    0
)

grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_정수"] = (
    grid_merge_hjd["문화누리대상자_성연령별_추정_인구수_floor"]
    + grid_merge_hjd["추가배분"]
)

int_check = (
    grid_merge_hjd
    .groupby("GRID_CD", as_index=False)
    .agg({
        "문화누리대상자_추정_인구수": "first",
        "문화누리대상자_성연령별_추정_인구수_정수": "sum"
    })
)

int_check["목표정수"] = int_check["문화누리대상자_추정_인구수"].round().astype(int)

int_check["정수화오차"] = (
    int_check["목표정수"]
    - int_check["문화누리대상자_성연령별_추정_인구수_정수"]
)

display(int_check["정수화오차"].describe())
print("정수화 오차 있는 격자 수:", (int_check["정수화오차"] != 0).sum())

count    60528.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: 정수화오차, dtype: float64

정수화 오차 있는 격자 수: 0

In [13]:
grid_mnc_age_gender_final = grid_merge_hjd[[
    "GRID_CD",
    "시군구",
    "행정동",
    "성별",
    "연령대",
    "문화누리대상자_성연령별_추정_인구수_정수"
]].copy()

grid_mnc_age_gender_final.rename(columns = {"문화누리대상자_성연령별_추정_인구수_정수": "문화누리대상자_성연령별_추정_인구수"}, 
                                 inplace=True,
                                 errors = 'ignore')



print(grid_mnc_age_gender_final.shape)
print(grid_mnc_age_gender_final.isna().sum())
print(grid_mnc_age_gender_final[["GRID_CD", "성별", "연령대"]].duplicated().sum())

display(grid_mnc_age_gender_final.head(30))

(1452672, 6)

GRID_CD                0
시군구                    0
행정동                    0
성별                     0
연령대                    0
문화누리대상자_성연령별_추정_인구수    0
dtype: int64

0

     GRID_CD  시군구   행정동  성별     연령대  문화누리대상자_성연령별_추정_인구수
0   다사603367  서초구  양재2동  남성    0-5세                    0
1   다사603367  서초구  양재2동  남성   100세-                    0
2   다사603367  서초구  양재2동  남성  15-19세                    0
3   다사603367  서초구  양재2동  남성  20-29세                    0
4   다사603367  서초구  양재2동  남성  30-39세                    0
5   다사603367  서초구  양재2동  남성  40-49세                    0
6   다사603367  서초구  양재2동  남성  50-59세                    0
7   다사603367  서초구  양재2동  남성   6-14세                    0
8   다사603367  서초구  양재2동  남성  60-69세                    0
9   다사603367  서초구  양재2동  남성  70-79세                    0
10  다사603367  서초구  양재2동  남성  80-89세                    0
11  다사603367  서초구  양재2동  남성  90-99세                    0
12  다사603367  서초구  양재2동  여성    0-5세                    0
13  다사603367  서초구  양재2동  여성   100세-                    0
14  다사603367  서초구  양재2동  여성  15-19세                    0
15  다사603367  서초구  양재2동  여성  20-29세                    0
16  다사603367  서초구  양재2동  여성  30-39세                    0
17  다사603367  서초구  양재2동  여성  40-49세                    0
18  다사603367  서초구  양재2동  여성  50-59세                    0
19  다사603367  서초구  양재2동  여성   6-14세                    0
20  다사603367  서초구  양재2동  여성  60-69세                    0
21  다사603367  서초구  양재2동  여성  70-79세                    0
22  다사603367  서초구  양재2동  여성  80-89세                    0
23  다사603367  서초구  양재2동  여성  90-99세                    0
24  다사604367  서초구  양재2동  남성    0-5세                    0
25  다사604367  서초구  양재2동  남성   100세-                    0
26  다사604367  서초구  양재2동  남성  15-19세                    0
27  다사604367  서초구  양재2동  남성  20-29세                    0
28  다사604367  서초구  양재2동  남성  30-39세                    0
29  다사604367  서초구  양재2동  남성  40-49세                    0

## 최종 결과 품질 점검

In [14]:
value_col = "문화누리대상자_성연령별_추정_인구수"

quality = pd.Series({
    "최종 행 수": len(grid_mnc_age_gender_final),
    "격자·성별·연령대 중복": int(
        grid_mnc_age_gender_final[["GRID_CD", "성별", "연령대"]]
        .duplicated().sum()
    ),
    "전체 결측": int(grid_mnc_age_gender_final.isna().sum().sum()),
    "음수 인구": int((grid_mnc_age_gender_final[value_col] < 0).sum()),
    "정수화 오차 격자": int((int_check["정수화오차"] != 0).sum()),
    "추정인구 합계": int(grid_mnc_age_gender_final[value_col].sum()),
}, name="확인값")

display(quality.to_frame())

assert quality["격자·성별·연령대 중복"] == 0
assert quality["전체 결측"] == 0
assert quality["음수 인구"] == 0
assert quality["정수화 오차 격자"] == 0

                  확인값
최종 행 수        1452672
격자·성별·연령대 중복        0
전체 결측               0
음수 인구               0
정수화 오차 격자           0
추정인구 합계        582441

## 결과 저장 및 요약

In [15]:
grid_mnc_age_gender_final.to_csv(
    OUTPUT_FILE,
    encoding="utf-8-sig",
    index=False,
)

saved = pd.read_csv(OUTPUT_FILE, encoding="utf-8-sig")
assert len(saved) == len(grid_mnc_age_gender_final)
assert saved.isna().sum().sum() == 0
assert saved[["GRID_CD", "성별", "연령대"]].duplicated().sum() == 0

summary = pd.Series({
    "저장 파일": OUTPUT_FILE.name,
    "행 수": f"{len(saved):,}",
    "격자 수": f"{saved['GRID_CD'].nunique():,}",
    "성별": ", ".join(saved["성별"].unique()),
    "연령대 수": saved["연령대"].nunique(),
    "추정인구 합계": f"{saved[value_col].sum():,}명",
    "결측값": int(saved.isna().sum().sum()),
    "중복": int(saved[["GRID_CD", "성별", "연령대"]].duplicated().sum()),
}, name="결과")
display(summary.to_frame())
print(f"저장 완료: {OUTPUT_FILE}")

                                       결과
저장 파일    서울시_격자_100m_문화누리대상자_성연령별_인구수.csv
행 수                             1,452,672
격자 수                               60,528
성별                                 남성, 여성
연령대 수                                  12
추정인구 합계                          582,441명
결측값                                     0
중복                                      0

저장 완료: C:\project\oracle_mnc_project\data\processed\estimated_target_population\서울시_격자_100m_문화누리대상자_성연령별_인구수.csv